spring:
  application:
    name: AUTHENTICATION-KEYCLOAK-SERVICE
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/auth_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/API-Realm
          jwk-set-uri: http://localhost:8180/realms/API-Realm/protocol/openid-connect/certs


